#############################################################################
# Makefile for building: daisi-gui
# Generated by qmake (2.01a) (Qt 4.8.7) on: Fri Mar 4 13:49:36 2016
# Project:  daisi-gui.pro
# Template: subdirs
# Command: /usr/bin/qmake-qt4 -spec /usr/lib64/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile daisi-gui.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake-qt4
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-libs \
		sub-fusion \
		sub-census-tool \
		sub-id-tool \
		sub-image-property-gui \
		sub-reference-gui \
		sub-image-server \
		sub-test-client

libs/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) libs/ || $(MKDIR) libs/ 
	cd libs/ && $(QMAKE) /home/awg/dev/daisi-gui/libs/libs.pro -spec /usr/lib64/qt4/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-libs-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) libs/ || $(MKDIR) libs/ 
	cd libs/ && $(QMAKE) /home/awg/dev/daisi-gui/libs/libs.pro -spec /usr/lib64/qt4/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-libs: libs/$(MAKEFILE) FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE)
sub-libs-make_default-ordered: libs/$(MAKEFILE) FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) 
sub-libs-make_default: libs/$(MAKEFILE) FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) 
sub-libs-make_first-ordered: libs/$(MAKEFILE) FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) first
sub-libs-make_first: libs/$(MAKEFILE) FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) first
sub-libs-all-ordered: libs/$(MAKEFILE) FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) all
sub-libs-all: libs/$(MAKEFILE) FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) all
sub-libs-clean-ordered: libs/$(MAKEFILE) FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) clean
sub-libs-clean: libs/$(MAKEFILE) FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) clean
sub-libs-distclean-ordered: libs/$(MAKEFILE) FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libs-distclean: libs/$(MAKEFILE) FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libs-install_subtargets-ordered: libs/$(MAKEFILE) FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) install
sub-libs-install_subtargets: libs/$(MAKEFILE) FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) install
sub-libs-uninstall_subtargets-ordered: libs/$(MAKEFILE) FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-libs-uninstall_subtargets: libs/$(MAKEFILE) FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) uninstall
fusion/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) fusion/ || $(MKDIR) fusion/ 
	cd fusion/ && $(QMAKE) /home/awg/dev/daisi-gui/fusion/fusion.pro -spec /usr/lib64/qt4/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-fusion-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) fusion/ || $(MKDIR) fusion/ 
	cd fusion/ && $(QMAKE) /home/awg/dev/daisi-gui/fusion/fusion.pro -spec /usr/lib64/qt4/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-fusion: fusion/$(MAKEFILE) FORCE
	cd fusion/ && $(MAKE) -f $(MAKEFILE)
sub-fusion-make_default-ordered: fusion/$(MAKEFILE) sub-libs-make_default-ordered  FORCE
	cd fusion/ && $(MAKE) -f $(MAKEFILE) 
sub-fusion-make_default: fusion/$(MAKEFILE) FORCE
	cd fusion/ && $(MAKE) -f $(MAKEFILE) 
sub-fusion-make_first-ordered: fusion/$(MAKEFILE) sub-libs-make_first-ordered  FORCE
	cd fusion/ && $(MAKE) -f $(MAKEFILE) first
sub-fusion-make_first: fusion/$(MAKEFILE) FORCE
	cd fusion/ && $(MAKE) -f $(MAKEFILE) first
sub-fusion-all-ordered: fusion/$(MAKEFILE) sub-libs-all-ordered  FORCE
	cd fusion/ && $(MAKE) -f $(MAKEFILE) all
sub-fusion-all: fusion/$(MAKEFILE) FORCE
	cd fusion/ && $(MAKE) -f $(MAKEFILE) all
sub-fusion-clean-ordered: fusion/$(MAKEFILE) sub-libs-clean-ordered  FORCE
	cd fusion/ && $(MAKE) -f $(MAKEFILE) clean
sub-fusion-clean: fusion/$(MAKEFILE) FORCE
	cd fusion/ && $(MAKE) -f $(MAKEFILE) clean
sub-fusion-distclean-ordered: fusion/$(MAKEFILE) sub-libs-distclean-ordered  FORCE
	cd fusion/ && $(MAKE) -f $(MAKEFILE) distclean
sub-fusion-distclean: fusion/$(MAKEFILE) FORCE
	cd fusion/ && $(MAKE) -f $(MAKEFILE) distclean
sub-fusion-install_subtargets-ordered: fusion/$(MAKEFILE) sub-libs-install_subtargets-ordered  FORCE
	cd fusion/ && $(MAKE) -f $(MAKEFILE) install
sub-fusion-install_subtargets: fusion/$(MAKEFILE) FORCE
	cd fusion/ && $(MAKE) -f $(MAKEFILE) install
sub-fusion-uninstall_subtargets-ordered: fusion/$(MAKEFILE) sub-libs-uninstall_subtargets-ordered  FORCE
	cd fusion/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-fusion-uninstall_subtargets: fusion/$(MAKEFILE) FORCE
	cd fusion/ && $(MAKE) -f $(MAKEFILE) uninstall
census-tool/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) census-tool/ || $(MKDIR) census-tool/ 
	cd census-tool/ && $(QMAKE) /home/awg/dev/daisi-gui/census-tool/census-tool.pro -spec /usr/lib64/qt4/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-census-tool-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) census-tool/ || $(MKDIR) census-tool/ 
	cd census-tool/ && $(QMAKE) /home/awg/dev/daisi-gui/census-tool/census-tool.pro -spec /usr/lib64/qt4/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-census-tool: census-tool/$(MAKEFILE) sub-libs \
		sub-fusion FORCE
	cd census-tool/ && $(MAKE) -f $(MAKEFILE)
sub-census-tool-make_default-ordered: census-tool/$(MAKEFILE) sub-fusion-make_default-ordered  FORCE
	cd census-tool/ && $(MAKE) -f $(MAKEFILE) 
sub-census-tool-make_default: census-tool/$(MAKEFILE) sub-libs-make_default sub-fusion-make_default FORCE
	cd census-tool/ && $(MAKE) -f $(MAKEFILE) 
sub-census-tool-make_first-ordered: census-tool/$(MAKEFILE) sub-fusion-make_first-ordered  FORCE
	cd census-tool/ && $(MAKE) -f $(MAKEFILE) first
sub-census-tool-make_first: census-tool/$(MAKEFILE) sub-libs-make_first sub-fusion-make_first FORCE
	cd census-tool/ && $(MAKE) -f $(MAKEFILE) first
sub-census-tool-all-ordered: census-tool/$(MAKEFILE) sub-fusion-all-ordered  FORCE
	cd census-tool/ && $(MAKE) -f $(MAKEFILE) all
sub-census-tool-all: census-tool/$(MAKEFILE) sub-libs-all sub-fusion-all FORCE
	cd census-tool/ && $(MAKE) -f $(MAKEFILE) all
sub-census-tool-clean-ordered: census-tool/$(MAKEFILE) sub-fusion-clean-ordered  FORCE
	cd census-tool/ && $(MAKE) -f $(MAKEFILE) clean
sub-census-tool-clean: census-tool/$(MAKEFILE) sub-libs-clean sub-fusion-clean FORCE
	cd census-tool/ && $(MAKE) -f $(MAKEFILE) clean
sub-census-tool-distclean-ordered: census-tool/$(MAKEFILE) sub-fusion-distclean-ordered  FORCE
	cd census-tool/ && $(MAKE) -f $(MAKEFILE) distclean
sub-census-tool-distclean: census-tool/$(MAKEFILE) sub-libs-distclean sub-fusion-distclean FORCE
	cd census-tool/ && $(MAKE) -f $(MAKEFILE) distclean
sub-census-tool-install_subtargets-ordered: census-tool/$(MAKEFILE) sub-fusion-install_subtargets-ordered  FORCE
	cd census-tool/ && $(MAKE) -f $(MAKEFILE) install
sub-census-tool-install_subtargets: census-tool/$(MAKEFILE) sub-libs-install_subtargets sub-fusion-install_subtargets FORCE
	cd census-tool/ && $(MAKE) -f $(MAKEFILE) install
sub-census-tool-uninstall_subtargets-ordered: census-tool/$(MAKEFILE) sub-fusion-uninstall_subtargets-ordered  FORCE
	cd census-tool/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-census-tool-uninstall_subtargets: census-tool/$(MAKEFILE) sub-libs-uninstall_subtargets sub-fusion-uninstall_subtargets FORCE
	cd census-tool/ && $(MAKE) -f $(MAKEFILE) uninstall
id-tool/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) id-tool/ || $(MKDIR) id-tool/ 
	cd id-tool/ && $(QMAKE) /home/awg/dev/daisi-gui/id-tool/id-tool.pro -spec /usr/lib64/qt4/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-id-tool-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) id-tool/ || $(MKDIR) id-tool/ 
	cd id-tool/ && $(QMAKE) /home/awg/dev/daisi-gui/id-tool/id-tool.pro -spec /usr/lib64/qt4/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-id-tool: id-tool/$(MAKEFILE) sub-libs \
		sub-fusion FORCE
	cd id-tool/ && $(MAKE) -f $(MAKEFILE)
sub-id-tool-make_default-ordered: id-tool/$(MAKEFILE) sub-census-tool-make_default-ordered  FORCE
	cd id-tool/ && $(MAKE) -f $(MAKEFILE) 
sub-id-tool-make_default: id-tool/$(MAKEFILE) sub-libs-make_default sub-fusion-make_default FORCE
	cd id-tool/ && $(MAKE) -f $(MAKEFILE) 
sub-id-tool-make_first-ordered: id-tool/$(MAKEFILE) sub-census-tool-make_first-ordered  FORCE
	cd id-tool/ && $(MAKE) -f $(MAKEFILE) first
sub-id-tool-make_first: id-tool/$(MAKEFILE) sub-libs-make_first sub-fusion-make_first FORCE
	cd id-tool/ && $(MAKE) -f $(MAKEFILE) first
sub-id-tool-all-ordered: id-tool/$(MAKEFILE) sub-census-tool-all-ordered  FORCE
	cd id-tool/ && $(MAKE) -f $(MAKEFILE) all
sub-id-tool-all: id-tool/$(MAKEFILE) sub-libs-all sub-fusion-all FORCE
	cd id-tool/ && $(MAKE) -f $(MAKEFILE) all
sub-id-tool-clean-ordered: id-tool/$(MAKEFILE) sub-census-tool-clean-ordered  FORCE
	cd id-tool/ && $(MAKE) -f $(MAKEFILE) clean
sub-id-tool-clean: id-tool/$(MAKEFILE) sub-libs-clean sub-fusion-clean FORCE
	cd id-tool/ && $(MAKE) -f $(MAKEFILE) clean
sub-id-tool-distclean-ordered: id-tool/$(MAKEFILE) sub-census-tool-distclean-ordered  FORCE
	cd id-tool/ && $(MAKE) -f $(MAKEFILE) distclean
sub-id-tool-distclean: id-tool/$(MAKEFILE) sub-libs-distclean sub-fusion-distclean FORCE
	cd id-tool/ && $(MAKE) -f $(MAKEFILE) distclean
sub-id-tool-install_subtargets-ordered: id-tool/$(MAKEFILE) sub-census-tool-install_subtargets-ordered  FORCE
	cd id-tool/ && $(MAKE) -f $(MAKEFILE) install
sub-id-tool-install_subtargets: id-tool/$(MAKEFILE) sub-libs-install_subtargets sub-fusion-install_subtargets FORCE
	cd id-tool/ && $(MAKE) -f $(MAKEFILE) install
sub-id-tool-uninstall_subtargets-ordered: id-tool/$(MAKEFILE) sub-census-tool-uninstall_subtargets-ordered  FORCE
	cd id-tool/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-id-tool-uninstall_subtargets: id-tool/$(MAKEFILE) sub-libs-uninstall_subtargets sub-fusion-uninstall_subtargets FORCE
	cd id-tool/ && $(MAKE) -f $(MAKEFILE) uninstall
image-property-gui/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) image-property-gui/ || $(MKDIR) image-property-gui/ 
	cd image-property-gui/ && $(QMAKE) /home/awg/dev/daisi-gui/image-property-gui/image-property-gui.pro -spec /usr/lib64/qt4/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-image-property-gui-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) image-property-gui/ || $(MKDIR) image-property-gui/ 
	cd image-property-gui/ && $(QMAKE) /home/awg/dev/daisi-gui/image-property-gui/image-property-gui.pro -spec /usr/lib64/qt4/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-image-property-gui: image-property-gui/$(MAKEFILE) sub-libs \
		sub-fusion FORCE
	cd image-property-gui/ && $(MAKE) -f $(MAKEFILE)
sub-image-property-gui-make_default-ordered: image-property-gui/$(MAKEFILE) sub-id-tool-make_default-ordered  FORCE
	cd image-property-gui/ && $(MAKE) -f $(MAKEFILE) 
sub-image-property-gui-make_default: image-property-gui/$(MAKEFILE) sub-libs-make_default sub-fusion-make_default FORCE
	cd image-property-gui/ && $(MAKE) -f $(MAKEFILE) 
sub-image-property-gui-make_first-ordered: image-property-gui/$(MAKEFILE) sub-id-tool-make_first-ordered  FORCE
	cd image-property-gui/ && $(MAKE) -f $(MAKEFILE) first
sub-image-property-gui-make_first: image-property-gui/$(MAKEFILE) sub-libs-make_first sub-fusion-make_first FORCE
	cd image-property-gui/ && $(MAKE) -f $(MAKEFILE) first
sub-image-property-gui-all-ordered: image-property-gui/$(MAKEFILE) sub-id-tool-all-ordered  FORCE
	cd image-property-gui/ && $(MAKE) -f $(MAKEFILE) all
sub-image-property-gui-all: image-property-gui/$(MAKEFILE) sub-libs-all sub-fusion-all FORCE
	cd image-property-gui/ && $(MAKE) -f $(MAKEFILE) all
sub-image-property-gui-clean-ordered: image-property-gui/$(MAKEFILE) sub-id-tool-clean-ordered  FORCE
	cd image-property-gui/ && $(MAKE) -f $(MAKEFILE) clean
sub-image-property-gui-clean: image-property-gui/$(MAKEFILE) sub-libs-clean sub-fusion-clean FORCE
	cd image-property-gui/ && $(MAKE) -f $(MAKEFILE) clean
sub-image-property-gui-distclean-ordered: image-property-gui/$(MAKEFILE) sub-id-tool-distclean-ordered  FORCE
	cd image-property-gui/ && $(MAKE) -f $(MAKEFILE) distclean
sub-image-property-gui-distclean: image-property-gui/$(MAKEFILE) sub-libs-distclean sub-fusion-distclean FORCE
	cd image-property-gui/ && $(MAKE) -f $(MAKEFILE) distclean
sub-image-property-gui-install_subtargets-ordered: image-property-gui/$(MAKEFILE) sub-id-tool-install_subtargets-ordered  FORCE
	cd image-property-gui/ && $(MAKE) -f $(MAKEFILE) install
sub-image-property-gui-install_subtargets: image-property-gui/$(MAKEFILE) sub-libs-install_subtargets sub-fusion-install_subtargets FORCE
	cd image-property-gui/ && $(MAKE) -f $(MAKEFILE) install
sub-image-property-gui-uninstall_subtargets-ordered: image-property-gui/$(MAKEFILE) sub-id-tool-uninstall_subtargets-ordered  FORCE
	cd image-property-gui/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-image-property-gui-uninstall_subtargets: image-property-gui/$(MAKEFILE) sub-libs-uninstall_subtargets sub-fusion-uninstall_subtargets FORCE
	cd image-property-gui/ && $(MAKE) -f $(MAKEFILE) uninstall
reference-gui/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) reference-gui/ || $(MKDIR) reference-gui/ 
	cd reference-gui/ && $(QMAKE) /home/awg/dev/daisi-gui/reference-gui/reference-gui.pro -spec /usr/lib64/qt4/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-reference-gui-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) reference-gui/ || $(MKDIR) reference-gui/ 
	cd reference-gui/ && $(QMAKE) /home/awg/dev/daisi-gui/reference-gui/reference-gui.pro -spec /usr/lib64/qt4/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-reference-gui: reference-gui/$(MAKEFILE) sub-libs \
		sub-fusion FORCE
	cd reference-gui/ && $(MAKE) -f $(MAKEFILE)
sub-reference-gui-make_default-ordered: reference-gui/$(MAKEFILE) sub-image-property-gui-make_default-ordered  FORCE
	cd reference-gui/ && $(MAKE) -f $(MAKEFILE) 
sub-reference-gui-make_default: reference-gui/$(MAKEFILE) sub-libs-make_default sub-fusion-make_default FORCE
	cd reference-gui/ && $(MAKE) -f $(MAKEFILE) 
sub-reference-gui-make_first-ordered: reference-gui/$(MAKEFILE) sub-image-property-gui-make_first-ordered  FORCE
	cd reference-gui/ && $(MAKE) -f $(MAKEFILE) first
sub-reference-gui-make_first: reference-gui/$(MAKEFILE) sub-libs-make_first sub-fusion-make_first FORCE
	cd reference-gui/ && $(MAKE) -f $(MAKEFILE) first
sub-reference-gui-all-ordered: reference-gui/$(MAKEFILE) sub-image-property-gui-all-ordered  FORCE
	cd reference-gui/ && $(MAKE) -f $(MAKEFILE) all
sub-reference-gui-all: reference-gui/$(MAKEFILE) sub-libs-all sub-fusion-all FORCE
	cd reference-gui/ && $(MAKE) -f $(MAKEFILE) all
sub-reference-gui-clean-ordered: reference-gui/$(MAKEFILE) sub-image-property-gui-clean-ordered  FORCE
	cd reference-gui/ && $(MAKE) -f $(MAKEFILE) clean
sub-reference-gui-clean: reference-gui/$(MAKEFILE) sub-libs-clean sub-fusion-clean FORCE
	cd reference-gui/ && $(MAKE) -f $(MAKEFILE) clean
sub-reference-gui-distclean-ordered: reference-gui/$(MAKEFILE) sub-image-property-gui-distclean-ordered  FORCE
	cd reference-gui/ && $(MAKE) -f $(MAKEFILE) distclean
sub-reference-gui-distclean: reference-gui/$(MAKEFILE) sub-libs-distclean sub-fusion-distclean FORCE
	cd reference-gui/ && $(MAKE) -f $(MAKEFILE) distclean
sub-reference-gui-install_subtargets-ordered: reference-gui/$(MAKEFILE) sub-image-property-gui-install_subtargets-ordered  FORCE
	cd reference-gui/ && $(MAKE) -f $(MAKEFILE) install
sub-reference-gui-install_subtargets: reference-gui/$(MAKEFILE) sub-libs-install_subtargets sub-fusion-install_subtargets FORCE
	cd reference-gui/ && $(MAKE) -f $(MAKEFILE) install
sub-reference-gui-uninstall_subtargets-ordered: reference-gui/$(MAKEFILE) sub-image-property-gui-uninstall_subtargets-ordered  FORCE
	cd reference-gui/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-reference-gui-uninstall_subtargets: reference-gui/$(MAKEFILE) sub-libs-uninstall_subtargets sub-fusion-uninstall_subtargets FORCE
	cd reference-gui/ && $(MAKE) -f $(MAKEFILE) uninstall
image-server/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) image-server/ || $(MKDIR) image-server/ 
	cd image-server/ && $(QMAKE) /home/awg/dev/daisi-gui/image-server/image-server.pro -spec /usr/lib64/qt4/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-image-server-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) image-server/ || $(MKDIR) image-server/ 
	cd image-server/ && $(QMAKE) /home/awg/dev/daisi-gui/image-server/image-server.pro -spec /usr/lib64/qt4/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-image-server: image-server/$(MAKEFILE) FORCE
	cd image-server/ && $(MAKE) -f $(MAKEFILE)
sub-image-server-make_default-ordered: image-server/$(MAKEFILE) sub-reference-gui-make_default-ordered  FORCE
	cd image-server/ && $(MAKE) -f $(MAKEFILE) 
sub-image-server-make_default: image-server/$(MAKEFILE) FORCE
	cd image-server/ && $(MAKE) -f $(MAKEFILE) 
sub-image-server-make_first-ordered: image-server/$(MAKEFILE) sub-reference-gui-make_first-ordered  FORCE
	cd image-server/ && $(MAKE) -f $(MAKEFILE) first
sub-image-server-make_first: image-server/$(MAKEFILE) FORCE
	cd image-server/ && $(MAKE) -f $(MAKEFILE) first
sub-image-server-all-ordered: image-server/$(MAKEFILE) sub-reference-gui-all-ordered  FORCE
	cd image-server/ && $(MAKE) -f $(MAKEFILE) all
sub-image-server-all: image-server/$(MAKEFILE) FORCE
	cd image-server/ && $(MAKE) -f $(MAKEFILE) all
sub-image-server-clean-ordered: image-server/$(MAKEFILE) sub-reference-gui-clean-ordered  FORCE
	cd image-server/ && $(MAKE) -f $(MAKEFILE) clean
sub-image-server-clean: image-server/$(MAKEFILE) FORCE
	cd image-server/ && $(MAKE) -f $(MAKEFILE) clean
sub-image-server-distclean-ordered: image-server/$(MAKEFILE) sub-reference-gui-distclean-ordered  FORCE
	cd image-server/ && $(MAKE) -f $(MAKEFILE) distclean
sub-image-server-distclean: image-server/$(MAKEFILE) FORCE
	cd image-server/ && $(MAKE) -f $(MAKEFILE) distclean
sub-image-server-install_subtargets-ordered: image-server/$(MAKEFILE) sub-reference-gui-install_subtargets-ordered  FORCE
	cd image-server/ && $(MAKE) -f $(MAKEFILE) install
sub-image-server-install_subtargets: image-server/$(MAKEFILE) FORCE
	cd image-server/ && $(MAKE) -f $(MAKEFILE) install
sub-image-server-uninstall_subtargets-ordered: image-server/$(MAKEFILE) sub-reference-gui-uninstall_subtargets-ordered  FORCE
	cd image-server/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-image-server-uninstall_subtargets: image-server/$(MAKEFILE) FORCE
	cd image-server/ && $(MAKE) -f $(MAKEFILE) uninstall
test-client/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) test-client/ || $(MKDIR) test-client/ 
	cd test-client/ && $(QMAKE) /home/awg/dev/daisi-gui/test-client/test-client.pro -spec /usr/lib64/qt4/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-test-client-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) test-client/ || $(MKDIR) test-client/ 
	cd test-client/ && $(QMAKE) /home/awg/dev/daisi-gui/test-client/test-client.pro -spec /usr/lib64/qt4/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-test-client: test-client/$(MAKEFILE) FORCE
	cd test-client/ && $(MAKE) -f $(MAKEFILE)
sub-test-client-make_default-ordered: test-client/$(MAKEFILE) sub-image-server-make_default-ordered  FORCE
	cd test-client/ && $(MAKE) -f $(MAKEFILE) 
sub-test-client-make_default: test-client/$(MAKEFILE) FORCE
	cd test-client/ && $(MAKE) -f $(MAKEFILE) 
sub-test-client-make_first-ordered: test-client/$(MAKEFILE) sub-image-server-make_first-ordered  FORCE
	cd test-client/ && $(MAKE) -f $(MAKEFILE) first
sub-test-client-make_first: test-client/$(MAKEFILE) FORCE
	cd test-client/ && $(MAKE) -f $(MAKEFILE) first
sub-test-client-all-ordered: test-client/$(MAKEFILE) sub-image-server-all-ordered  FORCE
	cd test-client/ && $(MAKE) -f $(MAKEFILE) all
sub-test-client-all: test-client/$(MAKEFILE) FORCE
	cd test-client/ && $(MAKE) -f $(MAKEFILE) all
sub-test-client-clean-ordered: test-client/$(MAKEFILE) sub-image-server-clean-ordered  FORCE
	cd test-client/ && $(MAKE) -f $(MAKEFILE) clean
sub-test-client-clean: test-client/$(MAKEFILE) FORCE
	cd test-client/ && $(MAKE) -f $(MAKEFILE) clean
sub-test-client-distclean-ordered: test-client/$(MAKEFILE) sub-image-server-distclean-ordered  FORCE
	cd test-client/ && $(MAKE) -f $(MAKEFILE) distclean
sub-test-client-distclean: test-client/$(MAKEFILE) FORCE
	cd test-client/ && $(MAKE) -f $(MAKEFILE) distclean
sub-test-client-install_subtargets-ordered: test-client/$(MAKEFILE) sub-image-server-install_subtargets-ordered  FORCE
	cd test-client/ && $(MAKE) -f $(MAKEFILE) install
sub-test-client-install_subtargets: test-client/$(MAKEFILE) FORCE
	cd test-client/ && $(MAKE) -f $(MAKEFILE) install
sub-test-client-uninstall_subtargets-ordered: test-client/$(MAKEFILE) sub-image-server-uninstall_subtargets-ordered  FORCE
	cd test-client/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-test-client-uninstall_subtargets: test-client/$(MAKEFILE) FORCE
	cd test-client/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: daisi-gui.pro  /usr/lib64/qt4/mkspecs/linux-g++/qmake.conf /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/debug.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/shared.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/lib64/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile daisi-gui.pro
/usr/lib64/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt4/mkspecs/common/g++-base.conf:
/usr/lib64/qt4/mkspecs/common/g++-unix.conf:
/usr/lib64/qt4/mkspecs/qconfig.pri:
/usr/lib64/qt4/mkspecs/modules/qt_webkit.pri:
/usr/lib64/qt4/mkspecs/features/qt_functions.prf:
/usr/lib64/qt4/mkspecs/features/qt_config.prf:
/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt4/mkspecs/features/default_pre.prf:
/usr/lib64/qt4/mkspecs/features/debug.prf:
/usr/lib64/qt4/mkspecs/features/default_post.prf:
/usr/lib64/qt4/mkspecs/features/shared.prf:
/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib64/qt4/mkspecs/features/warn_on.prf:
/usr/lib64/qt4/mkspecs/features/qt.prf:
/usr/lib64/qt4/mkspecs/features/unix/thread.prf:
/usr/lib64/qt4/mkspecs/features/moc.prf:
/usr/lib64/qt4/mkspecs/features/resources.prf:
/usr/lib64/qt4/mkspecs/features/uic.prf:
/usr/lib64/qt4/mkspecs/features/yacc.prf:
/usr/lib64/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec /usr/lib64/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile daisi-gui.pro

qmake_all: sub-libs-qmake_all sub-fusion-qmake_all sub-census-tool-qmake_all sub-id-tool-qmake_all sub-image-property-gui-qmake_all sub-reference-gui-qmake_all sub-image-server-qmake_all sub-test-client-qmake_all FORCE

make_default: sub-libs-make_default-ordered sub-fusion-make_default-ordered sub-census-tool-make_default-ordered sub-id-tool-make_default-ordered sub-image-property-gui-make_default-ordered sub-reference-gui-make_default-ordered sub-image-server-make_default-ordered sub-test-client-make_default-ordered FORCE
make_first: sub-libs-make_first-ordered sub-fusion-make_first-ordered sub-census-tool-make_first-ordered sub-id-tool-make_first-ordered sub-image-property-gui-make_first-ordered sub-reference-gui-make_first-ordered sub-image-server-make_first-ordered sub-test-client-make_first-ordered FORCE
all: sub-libs-all-ordered sub-fusion-all-ordered sub-census-tool-all-ordered sub-id-tool-all-ordered sub-image-property-gui-all-ordered sub-reference-gui-all-ordered sub-image-server-all-ordered sub-test-client-all-ordered FORCE
clean: sub-libs-clean-ordered sub-fusion-clean-ordered sub-census-tool-clean-ordered sub-id-tool-clean-ordered sub-image-property-gui-clean-ordered sub-reference-gui-clean-ordered sub-image-server-clean-ordered sub-test-client-clean-ordered FORCE
distclean: sub-libs-distclean-ordered sub-fusion-distclean-ordered sub-census-tool-distclean-ordered sub-id-tool-distclean-ordered sub-image-property-gui-distclean-ordered sub-reference-gui-distclean-ordered sub-image-server-distclean-ordered sub-test-client-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-libs-install_subtargets-ordered sub-fusion-install_subtargets-ordered sub-census-tool-install_subtargets-ordered sub-id-tool-install_subtargets-ordered sub-image-property-gui-install_subtargets-ordered sub-reference-gui-install_subtargets-ordered sub-image-server-install_subtargets-ordered sub-test-client-install_subtargets-ordered FORCE
uninstall_subtargets: sub-libs-uninstall_subtargets-ordered sub-fusion-uninstall_subtargets-ordered sub-census-tool-uninstall_subtargets-ordered sub-id-tool-uninstall_subtargets-ordered sub-image-property-gui-uninstall_subtargets-ordered sub-reference-gui-uninstall_subtargets-ordered sub-image-server-uninstall_subtargets-ordered sub-test-client-uninstall_subtargets-ordered FORCE

sub-libs-check_ordered: libs/$(MAKEFILE)
	cd libs/ && $(MAKE) -f $(MAKEFILE) check
sub-fusion-check_ordered: fusion/$(MAKEFILE) sub-libs-check_ordered 
	cd fusion/ && $(MAKE) -f $(MAKEFILE) check
sub-census-tool-check_ordered: census-tool/$(MAKEFILE) sub-fusion-check_ordered 
	cd census-tool/ && $(MAKE) -f $(MAKEFILE) check
sub-id-tool-check_ordered: id-tool/$(MAKEFILE) sub-census-tool-check_ordered 
	cd id-tool/ && $(MAKE) -f $(MAKEFILE) check
sub-image-property-gui-check_ordered: image-property-gui/$(MAKEFILE) sub-id-tool-check_ordered 
	cd image-property-gui/ && $(MAKE) -f $(MAKEFILE) check
sub-reference-gui-check_ordered: reference-gui/$(MAKEFILE) sub-image-property-gui-check_ordered 
	cd reference-gui/ && $(MAKE) -f $(MAKEFILE) check
sub-image-server-check_ordered: image-server/$(MAKEFILE) sub-reference-gui-check_ordered 
	cd image-server/ && $(MAKE) -f $(MAKEFILE) check
sub-test-client-check_ordered: test-client/$(MAKEFILE) sub-image-server-check_ordered 
	cd test-client/ && $(MAKE) -f $(MAKEFILE) check
check: sub-libs-check_ordered sub-fusion-check_ordered sub-census-tool-check_ordered sub-id-tool-check_ordered sub-image-property-gui-check_ordered sub-reference-gui-check_ordered sub-image-server-check_ordered sub-test-client-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

